# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import users_pb2 as users__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in users_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UsersStub(object):
    """A gRPC service for `Users`.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IsValidToken = channel.unary_unary(
                '/Users/IsValidToken',
                request_serializer=users__pb2.AuthTokenRequest.SerializeToString,
                response_deserializer=users__pb2.AuthTokenIsValid.FromString,
                _registered_method=True)


class UsersServicer(object):
    """A gRPC service for `Users`.
    """

    def IsValidToken(self, request, context):
        """Check if a provided Auth token is valid.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UsersServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IsValidToken': grpc.unary_unary_rpc_method_handler(
                    servicer.IsValidToken,
                    request_deserializer=users__pb2.AuthTokenRequest.FromString,
                    response_serializer=users__pb2.AuthTokenIsValid.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Users', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Users', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Users(object):
    """A gRPC service for `Users`.
    """

    @staticmethod
    def IsValidToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Users/IsValidToken',
            users__pb2.AuthTokenRequest.SerializeToString,
            users__pb2.AuthTokenIsValid.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
